version: '3.0'
services:      
  api-catalog-db:
    container_name: api-catalog-db
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: 'flights_catalog'
      MYSQL_USER: 'root'
      MYSQL_PASSWORD: 'muppet'
      MYSQL_ROOT_PASSWORD: 'muppet'
    ports:
     - 3310:3306

  api-clusters-remote-cache:
    container_name: api-clusters-remote-cache
    image: redis:alpine
    restart: always
    ports:
     - 5079:6379
     
  api-pricing-db:
    container_name: api-pricing-db
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: 'flights_pricing'
      MYSQL_USER: 'root'
      MYSQL_PASSWORD: 'muppet'
      MYSQL_ROOT_PASSWORD: 'muppet'        
    ports:
     - 3311:3306
