management:
  health.db.enabled: false
  endpoints:    
    web:
      base-path: /
      exposure:
        include: "*"

server:
  port: 9070
  servlet:
    context-path: /api/flights/provider/beta

jetty:
  threadPool:
    maxThreads: 10
    minThreads: 10

spring:
  profiles:
    active: default
        
connector:
   catalog:
      host: api-catalog:6070
      responseTimeout: 1000
      connectionTimeout: 1000
      readTimeout: 1000