management:
  health.db.enabled: false
  endpoints:    
    web:
      base-path: /
      exposure:
        include: "*"

server:
  port: 4070
  servlet:
    context-path: /api/flights/clusters

jetty:
  threadPool:
    maxThreads: 10
    minThreads: 10

chaos:
  monkey:
    enabled: false
    watcher:
      restController: true
    assaults:
      exceptionsActive: true
      latencyActive: true   
      latencyRangeStart: 10
      latencyRangeEnd: 5000  
      
spring:
  profiles:
    active: default
  jackson:
    default-property-inclusion: non_null

redis:
  host: api-clusters-remote-cache
  port: 6379

cache:
  settings:
    catalog-city:
      expire-after-write-time: 60 # minutes

connector:
   catalog:
      host: api-catalog-varnish:80
      responseTimeout: 2000
      connectionTimeout: 2000
      readTimeout: 2000
   pricing:
      host: api-pricing:5070
      responseTimeout: 10000
      connectionTimeout: 10000
      readTimeout: 10000   
   itineraries-search:
      host: api-itineraries-search:7070
      responseTimeout: 10000
      connectionTimeout: 10000
      readTimeout: 10000         