management:
  health.db.enabled: false
  endpoints:    
    web:
      base-path: /
      exposure:
        include: "*"

server:
  port: 7070
  servlet:
    context-path: /api/flights/itineraries-search

jetty:
  threadPool:
    maxThreads: 10
    minThreads: 10

spring:
  profiles:
    active: default

connector:  
   provider-alpha:
      host: localhost:8070
      responseTimeout: 5000
      connectionTimeout: 5000
      readTimeout: 5000         
   provider-beta:
      host: localhost:9070
      responseTimeout: 5000
      connectionTimeout: 5000
      readTimeout: 5000 